meyveler=["elma","armut","kiraz"]
sebzeler=["Kereviz","Lahana","Pırasa"]
print(meyveler)
meyveler.append("karpuz")
print(meyveler)
alinacaklar=meyveler+sebzeler
print(alinacaklar)
print(alinacaklar[2])
print(alinacaklar[2:])
print(alinacaklar[:2])
print(alinacaklar[2:4])
